services:
  api:
    # แทนที่จะใช้ Dockerfile ปกติ ให้ใช้ Image ที่มี JDK สำหรับ Dev
    image: maven:3.9.6-eclipse-temurin-21-alpine
    working_dir: /app
    volumes:
      - .:/app  # เชื่อมโค้ดทั้งหมด (รวม mvnw และ src)
      - ~/.m2:/root/.m2 # เก็บ Cache ของ Maven ไว้จะได้ไม่ต้องโหลดใหม่บ่อยๆ
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"

  frontend:
    # ใช้ Node image แทน Nginx
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules # สำคัญ! ป้องกันไม่ให้ node_modules ในเครื่องเราไปทับใน Container
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173" # พอร์ตมาตรฐานของ Vite

  nginx:
    # Use the official Nginx lightweight alpine image
    image: nginx:alpine
    # Map port 23000 on your local machine to port 23000 on the container
    ports:
      - "23000:23000"
    # Mount our local nginx.conf into the container so it knows our routing rules
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx-proxy

  
    # Ensure Nginx waits for the API and Frontend to start up first before it starts
    depends_on:
      - api
      - frontend
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/nolanrobinson/.docker/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer_data:/data