# docker-compose.yml allows you to orchestrate multiple containers together.
# In this case, we orchestrate the Nginx web server and the Spring Boot API.
version: '3.8'

services:
  # 1. The Spring Boot backend service
  api:
    # Build the image using the Dockerfile in the current directory (".")
    build: .
    # Note: We purposely DO NOT map ports to the host machine here (like ports: 8080:8080).
    # We want all requests to go strictly through Nginx first. The containers can still talk to each other.
    expose:
      - "8080"
    # Gives the container a recognizable name
    container_name: spring-boot-api

    #Bind mount the target directory to the container
    volumes:
      - .:/app
    
    command: ./mvnw spring-boot:run

    # Restarts automatically unless explicitly completely stopped
    restart: unless-stopped

  # 2. The React Frontend service
  frontend:
    build: ./frontend
    expose:
      - "80"
    container_name: react-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  # 3. The Nginx reverse proxy service
  nginx:
    # Use the official Nginx lightweight alpine image
    image: nginx:alpine
    # Map port 23000 on your local machine to port 23000 on the container
    ports:
      - "23000:23000"
    # Mount our local nginx.conf into the container so it knows our routing rules
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx-proxy

  
    # Ensure Nginx waits for the API and Frontend to start up first before it starts
    depends_on:
      - api
      - frontend
    restart: unless-stopped

  # 4. Portainer for easy Docker management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /Users/nolanrobinson/.docker/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer_data:/data
